spring:
  application:
    name: mail-service
  freemarker:
    checkTemplateLocation: false
  sendgrid:
    api-key:
    properties:
      sender:
        name: Constantinos Giannacoulis
      username:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SMTP_USERNAME}
    password: ${MAIL_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      sender:
        name: Constantinos Giannacoulis
    protocol: smtp
    test-connection: false
server:
  port: 10200

eureka:
  client:
    fetch-registry: true
    refresh:
      enable: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8100/eureka/
    rest-template-timeout:
      connect-timeout: 5000
      connect-request-timeout: 8000
      socket-timeout: 10000
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}-${random.value}
